---
title: pwacafe
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  barber:
    title: barber
    output: true
  coffeeshop:
    title: coffeeshop
    output: true
  mechanic:
    title: mechanic
    output: true
  restaurant:
    title: restaurant
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
url: www.pwacafe.siteleaf.net
catagories:
- restaurant
- coffeeshop
- mechanic
- barber
